package icons

import "github.com/lucax88x/wentsketchy/cmd/cli/config/settings"

// https://github.com/kvndrsslr/sketchybar-app-font/releases
var App = map[string]IconInfo{
	"Live":                             {Icon: ":ableton:", Font: settings.FontAppIcon},
	"Adobe Bridge":                     {Icon: ":adobe_bridge:", Font: settings.FontAppIcon},
	"Affinity Designer":                {Icon: ":affinity_designer:", Font: settings.FontAppIcon},
	"Affinity Designer 2":              {Icon: ":affinity_designer_2:", Font: settings.FontAppIcon},
	"Affinity Photo":                   {Icon: ":affinity_photo:", Font: settings.FontAppIcon},
	"Affinity Photo 2":                 {Icon: ":affinity_photo_2:", Font: settings.FontAppIcon},
	"Affinity Publisher":               {Icon: ":affinity_publisher:", Font: settings.FontAppIcon},
	"Affinity Publisher 2":             {Icon: ":affinity_publisher_2:", Font: settings.FontAppIcon},
	"Airmail":                          {Icon: ":airmail:", Font: settings.FontAppIcon},
	"Alacritty":                        {Icon: ":alacritty:", Font: settings.FontAppIcon},
	"Alfred":                           {Icon: ":alfred:", Font: settings.FontAppIcon},
	"Android Messages":                 {Icon: ":android_messages:", Font: settings.FontAppIcon},
	"Android Studio":                   {Icon: ":android_studio:", Font: settings.FontAppIcon},
	"Anytype":                          {Icon: ":anytype:", Font: settings.FontAppIcon},
	"App Eraser":                       {Icon: ":app_eraser:", Font: settings.FontAppIcon},
	"App Store":                        {Icon: ":app_store:", Font: settings.FontAppIcon},
	"Arc":                              {Icon: ":arc:", Font: settings.FontAppIcon},
	"Atom":                             {Icon: ":atom:", Font: settings.FontAppIcon},
	"Audacity":                         {Icon: ":audacity:", Font: settings.FontAppIcon},
	"Bambu Studio":                     {Icon: ":bambu_studio:", Font: settings.FontAppIcon},
	"MoneyMoney":                       {Icon: ":bank:", Font: settings.FontAppIcon},
	"Battle.net":                       {Icon: ":battle_net:", Font: settings.FontAppIcon},
	"Bear":                             {Icon: ":bear:", Font: settings.FontAppIcon},
	"BetterTouchTool":                  {Icon: ":bettertouchtool:", Font: settings.FontAppIcon},
	"Bilibili":                         {Icon: ":bilibili:", Font: settings.FontAppIcon},
	"哔哩哔哩":                             {Icon: ":bilibili:", Font: settings.FontAppIcon},
	"Bitwarden":                        {Icon: ":bit_warden:", Font: settings.FontAppIcon},
	"Blender":                          {Icon: ":blender:", Font: settings.FontAppIcon},
	"BluOS Controller":                 {Icon: ":bluos_controller:", Font: settings.FontAppIcon},
	"Calibre":                          {Icon: ":book:", Font: settings.FontAppIcon},
	"Brave Browser":                    {Icon: ":brave_browser:", Font: settings.FontAppIcon},
	"BusyCal":                          {Icon: ":busycal:", Font: settings.FontAppIcon},
	"Calculator":                       {Icon: ":calculator:", Font: settings.FontAppIcon},
	"Calculette":                       {Icon: ":calculator:", Font: settings.FontAppIcon},
	"Calendar":                         {Icon: ":calendar:", Font: settings.FontAppIcon},
	"日历":                               {Icon: ":calendar:", Font: settings.FontAppIcon},
	"Fantastical":                      {Icon: ":calendar:", Font: settings.FontAppIcon},
	"Cron":                             {Icon: ":calendar:", Font: settings.FontAppIcon},
	"Amie":                             {Icon: ":calendar:", Font: settings.FontAppIcon},
	"Calendrier":                       {Icon: ":calendar:", Font: settings.FontAppIcon},
	"Notion Calendar":                  {Icon: ":calendar:", Font: settings.FontAppIcon},
	"Caprine":                          {Icon: ":caprine:", Font: settings.FontAppIcon},
	"Citrix Workspace":                 {Icon: ":citrix:", Font: settings.FontAppIcon},
	"Citrix Viewer":                    {Icon: ":citrix:", Font: settings.FontAppIcon},
	"ClickUp":                          {Icon: ":click_up:", Font: settings.FontAppIcon},
	"Code":                             {Icon: ":code:", Font: settings.FontAppIcon},
	"Code - Insiders":                  {Icon: ":code:", Font: settings.FontAppIcon},
	"Void":                             {Icon: ":code:", Font: settings.FontAppIcon},
	"Color Picker":                     {Icon: ":color_picker:", Font: settings.FontAppIcon},
	"数码测色计":                            {Icon: ":color_picker:", Font: settings.FontAppIcon},
	"CotEditor":                        {Icon: ":coteditor:", Font: settings.FontAppIcon},
	"Creative Cloud":                   {Icon: ":creative_cloud:", Font: settings.FontAppIcon},
	"Cypress":                          {Icon: ":cypress:", Font: settings.FontAppIcon},
	"DataGrip":                         {Icon: ":datagrip:", Font: settings.FontAppIcon},
	"DataSpell":                        {Icon: ":dataspell:", Font: settings.FontAppIcon},
	"DaVinci Resolve":                  {Icon: ":davinciresolve:", Font: settings.FontAppIcon},
	"Deezer":                           {Icon: ":deezer:", Font: settings.FontAppIcon},
	"Default":                          {Icon: ":default:", Font: settings.FontAppIcon},
	"CleanMyMac X":                     {Icon: ":desktop:", Font: settings.FontAppIcon},
	"DEVONthink 3":                     {Icon: ":devonthink3:", Font: settings.FontAppIcon},
	"DingTalk":                         {Icon: ":dingtalk:", Font: settings.FontAppIcon},
	"钉钉":                               {Icon: ":dingtalk:", Font: settings.FontAppIcon},
	"阿里钉":                              {Icon: ":dingtalk:", Font: settings.FontAppIcon},
	"Discord":                          {Icon: ":discord:", Font: settings.FontAppIcon},
	"Discord Canary":                   {Icon: ":discord:", Font: settings.FontAppIcon},
	"Discord PTB":                      {Icon: ":discord:", Font: settings.FontAppIcon},
	"Docker":                           {Icon: ":docker:", Font: settings.FontAppIcon},
	"Docker Desktop":                   {Icon: ":docker:", Font: settings.FontAppIcon},
	"GrandTotal":                       {Icon: ":dollar:", Font: settings.FontAppIcon},
	"Receipts":                         {Icon: ":dollar:", Font: settings.FontAppIcon},
	"Double Commander":                 {Icon: ":doublecmd:", Font: settings.FontAppIcon},
	"Drafts":                           {Icon: ":drafts:", Font: settings.FontAppIcon},
	"Dropbox":                          {Icon: ":dropbox:", Font: settings.FontAppIcon},
	"Element":                          {Icon: ":element:", Font: settings.FontAppIcon},
	"Emacs":                            {Icon: ":emacs:", Font: settings.FontAppIcon},
	"Evernote Legacy":                  {Icon: ":evernote_legacy:", Font: settings.FontAppIcon},
	"FaceTime":                         {Icon: ":face_time:", Font: settings.FontAppIcon},
	"FaceTime 通话":                      {Icon: ":face_time:", Font: settings.FontAppIcon},
	"Figma":                            {Icon: ":figma:", Font: settings.FontAppIcon},
	"Final Cut Pro":                    {Icon: ":final_cut_pro:", Font: settings.FontAppIcon},
	"Finder":                           {Icon: ":finder:", Font: settings.FontAppIcon},
	"访达":                               {Icon: ":finder:", Font: settings.FontAppIcon},
	"Firefox":                          {Icon: ":firefox:", Font: settings.FontAppIcon},
	"Firefox Developer Edition":        {Icon: ":firefox_developer_edition:", Font: settings.FontAppIcon},
	"Firefox Nightly":                  {Icon: ":firefox_developer_edition:", Font: settings.FontAppIcon},
	"Folx":                             {Icon: ":folx:", Font: settings.FontAppIcon},
	"Fork":                             {Icon: ":fork:", Font: settings.FontAppIcon},
	"Fusion":                           {Icon: ":fusion:", Font: settings.FontAppIcon},
	"System Preferences":               {Icon: ":gear:", Font: settings.FontAppIcon},
	"System Settings":                  {Icon: ":gear:", Font: settings.FontAppIcon},
	"系统设置":                             {Icon: ":gear:", Font: settings.FontAppIcon},
	"Réglages Système":                 {Icon: ":gear:", Font: settings.FontAppIcon},
	"GitHub Desktop":                   {Icon: ":git_hub:", Font: settings.FontAppIcon},
	"Godot":                            {Icon: ":godot:", Font: settings.FontAppIcon},
	"GoLand":                           {Icon: ":goland:", Font: settings.FontAppIcon},
	"Chromium":                         {Icon: ":google_chrome:", Font: settings.FontAppIcon},
	"Google Chrome":                    {Icon: ":google_chrome:", Font: settings.FontAppIcon},
	"Google Chrome Canary":             {Icon: ":google_chrome:", Font: settings.FontAppIcon},
	"Grammarly Editor":                 {Icon: ":grammarly:", Font: settings.FontAppIcon},
	"Home Assistant":                   {Icon: ":home_assistant:", Font: settings.FontAppIcon},
	"Hyper":                            {Icon: ":hyper:", Font: settings.FontAppIcon},
	"IntelliJ IDEA":                    {Icon: ":idea:", Font: settings.FontAppIcon},
	"Adobe Illustrator":                {Icon: ":illustrator:", Font: settings.FontAppIcon},
	"Illustrator":                      {Icon: ":illustrator:", Font: settings.FontAppIcon},
	"Adobe InDesign":                   {Icon: ":indesign:", Font: settings.FontAppIcon},
	"InDesign":                         {Icon: ":indesign:", Font: settings.FontAppIcon},
	"Inkdrop":                          {Icon: ":inkdrop:", Font: settings.FontAppIcon},
	"Inkscape":                         {Icon: ":inkscape:", Font: settings.FontAppIcon},
	"Insomnia":                         {Icon: ":insomnia:", Font: settings.FontAppIcon},
	"Instagram":                        {Icon: "", Font: settings.FontIcon},
	"Iris":                             {Icon: ":iris:", Font: settings.FontAppIcon},
	"iTerm":                            {Icon: ":iterm:", Font: settings.FontAppIcon},
	"iTerm2":                           {Icon: ":iterm:", Font: settings.FontAppIcon},
	"Jellyfin Media Player":            {Icon: ":jellyfin:", Font: settings.FontAppIcon},
	"Joplin":                           {Icon: ":joplin:", Font: settings.FontAppIcon},
	"카카오톡":                             {Icon: ":kakaotalk:", Font: settings.FontAppIcon},
	"KakaoTalk":                        {Icon: ":kakaotalk:", Font: settings.FontAppIcon},
	"Kakoune":                          {Icon: ":kakoune:", Font: settings.FontAppIcon},
	"KeePassXC":                        {Icon: ":kee_pass_x_c:", Font: settings.FontAppIcon},
	"Keyboard Maestro":                 {Icon: ":keyboard_maestro:", Font: settings.FontAppIcon},
	"Keynote":                          {Icon: ":keynote:", Font: settings.FontAppIcon},
	"Keynote 讲演":                       {Icon: ":keynote:", Font: settings.FontAppIcon},
	"kitty":                            {Icon: ":kitty:", Font: settings.FontAppIcon},
	"League of Legends":                {Icon: ":league_of_legends:", Font: settings.FontAppIcon},
	"LibreWolf":                        {Icon: ":libre_wolf:", Font: settings.FontAppIcon},
	"Adobe Lightroom":                  {Icon: ":lightroom:", Font: settings.FontAppIcon},
	"Lightroom Classic":                {Icon: ":lightroomclassic:", Font: settings.FontAppIcon},
	"LINE":                             {Icon: ":line:", Font: settings.FontAppIcon},
	"Linear":                           {Icon: ":linear:", Font: settings.FontAppIcon},
	"LM Studio":                        {Icon: ":lm_studio:", Font: settings.FontAppIcon},
	"LocalSend":                        {Icon: ":localsend:", Font: settings.FontAppIcon},
	"Logic Pro":                        {Icon: ":logicpro:", Font: settings.FontAppIcon},
	"Logseq":                           {Icon: ":logseq:", Font: settings.FontAppIcon},
	"Canary Mail":                      {Icon: ":mail:", Font: settings.FontAppIcon},
	"HEY":                              {Icon: ":mail:", Font: settings.FontAppIcon},
	"Mail":                             {Icon: ":mail:", Font: settings.FontAppIcon},
	"Mailspring":                       {Icon: ":mail:", Font: settings.FontAppIcon},
	"MailMate":                         {Icon: ":mail:", Font: settings.FontAppIcon},
	"Superhuman":                       {Icon: ":mail:", Font: settings.FontAppIcon},
	"Spark":                            {Icon: ":mail:", Font: settings.FontAppIcon},
	"邮件":                               {Icon: ":mail:", Font: settings.FontAppIcon},
	"MAMP":                             {Icon: ":mamp:", Font: settings.FontAppIcon},
	"MAMP PRO":                         {Icon: ":mamp:", Font: settings.FontAppIcon},
	"Maps":                             {Icon: ":maps:", Font: settings.FontAppIcon},
	"Google Maps":                      {Icon: ":maps:", Font: settings.FontAppIcon},
	"Marta":                            {Icon: ":marta:", Font: settings.FontAppIcon},
	"Matlab":                           {Icon: ":matlab:", Font: settings.FontAppIcon},
	"Mattermost":                       {Icon: ":mattermost:", Font: settings.FontAppIcon},
	"Messages":                         {Icon: ":messages:", Font: settings.FontAppIcon},
	"信息":                               {Icon: ":messages:", Font: settings.FontAppIcon},
	"Nachrichten":                      {Icon: ":messages:", Font: settings.FontAppIcon},
	"Messenger":                        {Icon: ":messenger:", Font: settings.FontAppIcon},
	"Microsoft Edge":                   {Icon: ":microsoft_edge:", Font: settings.FontAppIcon},
	"Microsoft Excel":                  {Icon: ":microsoft_excel:", Font: settings.FontAppIcon},
	"Microsoft Outlook":                {Icon: ":microsoft_outlook:", Font: settings.FontAppIcon},
	"Microsoft PowerPoint":             {Icon: ":microsoft_power_point:", Font: settings.FontAppIcon},
	"Microsoft Remote Desktop":         {Icon: ":microsoft_remote_desktop:", Font: settings.FontAppIcon},
	"Microsoft Teams":                  {Icon: ":microsoft_teams:", Font: settings.FontAppIcon},
	"Microsoft Teams (work or school)": {Icon: ":microsoft_teams:", Font: settings.FontAppIcon},
	"Microsoft Word":                   {Icon: ":microsoft_word:", Font: settings.FontAppIcon},
	"Min":                              {Icon: ":min_browser:", Font: settings.FontAppIcon},
	"Miro":                             {Icon: ":miro:", Font: settings.FontAppIcon},
	"MongoDB Compass":                  {Icon: ":mongodb:", Font: settings.FontAppIcon},
	"mpv":                              {Icon: ":mpv:", Font: settings.FontAppIcon},
	"Mullvad Browser":                  {Icon: ":mullvad_browser:", Font: settings.FontAppIcon},
	"Music":                            {Icon: ":music:", Font: settings.FontAppIcon},
	"音乐":                               {Icon: ":music:", Font: settings.FontAppIcon},
	"Musique":                          {Icon: ":music:", Font: settings.FontAppIcon},
	"Neovide":                          {Icon: ":neovide:", Font: settings.FontAppIcon},
	"neovide":                          {Icon: ":neovide:", Font: settings.FontAppIcon},
	"Neovim":                           {Icon: ":neovim:", Font: settings.FontAppIcon},
	"neovim":                           {Icon: ":neovim:", Font: settings.FontAppIcon},
	"nvim":                             {Icon: ":neovim:", Font: settings.FontAppIcon},
	"网易云音乐":                            {Icon: ":netease_music:", Font: settings.FontAppIcon},
	"Noodl":                            {Icon: ":noodl:", Font: settings.FontAppIcon},
	"Noodl Editor":                     {Icon: ":noodl:", Font: settings.FontAppIcon},
	"NordVPN":                          {Icon: ":nord_vpn:", Font: settings.FontAppIcon},
	"Notability":                       {Icon: ":notability:", Font: settings.FontAppIcon},
	"Notes":                            {Icon: ":notes:", Font: settings.FontAppIcon},
	"备忘录":                              {Icon: ":notes:", Font: settings.FontAppIcon},
	"Notion":                           {Icon: ":notion:", Font: settings.FontAppIcon},
	"Nova":                             {Icon: ":nova:", Font: settings.FontAppIcon},
	"Numbers":                          {Icon: ":numbers:", Font: settings.FontAppIcon},
	"Numbers 表格":                       {Icon: ":numbers:", Font: settings.FontAppIcon},
	"Obsidian":                         {Icon: ":obsidian:", Font: settings.FontAppIcon},
	"OBS":                              {Icon: ":obsstudio:", Font: settings.FontAppIcon},
	"OmniFocus":                        {Icon: ":omni_focus:", Font: settings.FontAppIcon},
	"1Password":                        {Icon: ":one_password:", Font: settings.FontAppIcon},
	"Open Video Downloader":            {Icon: ":open_video_downloader:", Font: settings.FontAppIcon},
	"ChatGPT":                          {Icon: ":openai:", Font: settings.FontAppIcon},
	"OpenVPN Connect":                  {Icon: ":openvpn_connect:", Font: settings.FontAppIcon},
	"Opera":                            {Icon: ":opera:", Font: settings.FontAppIcon},
	"OrcaSlicer":                       {Icon: ":orcaslicer:", Font: settings.FontAppIcon},
	"Orion":                            {Icon: ":orion:", Font: settings.FontAppIcon},
	"Orion RC":                         {Icon: ":orion:", Font: settings.FontAppIcon},
	"Pages":                            {Icon: ":pages:", Font: settings.FontAppIcon},
	"Pages 文稿":                         {Icon: ":pages:", Font: settings.FontAppIcon},
	"Parallels Desktop":                {Icon: ":parallels:", Font: settings.FontAppIcon},
	"Parsec":                           {Icon: ":parsec:", Font: settings.FontAppIcon},
	"Preview":                          {Icon: ":pdf:", Font: settings.FontAppIcon},
	"预览":                               {Icon: ":pdf:", Font: settings.FontAppIcon},
	"Skim":                             {Icon: ":pdf:", Font: settings.FontAppIcon},
	"zathura":                          {Icon: ":pdf:", Font: settings.FontAppIcon},
	"Aperçu":                           {Icon: ":pdf:", Font: settings.FontAppIcon},
	"PDF Expert":                       {Icon: ":pdf_expert:", Font: settings.FontAppIcon},
	"Adobe Photoshop":                  {Icon: ":photoshop:", Font: settings.FontAppIcon},
	"PhpStorm":                         {Icon: ":php_storm:", Font: settings.FontAppIcon},
	"Pi-hole Remote":                   {Icon: ":pihole:", Font: settings.FontAppIcon},
	"Pine":                             {Icon: ":pine:", Font: settings.FontAppIcon},
	"Podcasts":                         {Icon: ":podcasts:", Font: settings.FontAppIcon},
	"播客":                               {Icon: ":podcasts:", Font: settings.FontAppIcon},
	"PomoDone App":                     {Icon: ":pomodone:", Font: settings.FontAppIcon},
	"Postman":                          {Icon: ":postman:", Font: settings.FontAppIcon},
	"Proton Mail":                      {Icon: ":proton_mail:", Font: settings.FontAppIcon},
	"Proton Mail Bridge":               {Icon: ":proton_mail:", Font: settings.FontAppIcon},
	"PrusaSlicer":                      {Icon: ":prusaslicer:", Font: settings.FontAppIcon},
	"SuperSlicer":                      {Icon: ":prusaslicer:", Font: settings.FontAppIcon},
	"PyCharm":                          {Icon: ":pycharm:", Font: settings.FontAppIcon},
	"QQ":                               {Icon: ":qq:", Font: settings.FontAppIcon},
	"QQ音乐":                             {Icon: ":qqmusic:", Font: settings.FontAppIcon},
	"QQMusic":                          {Icon: ":qqmusic:", Font: settings.FontAppIcon},
	"Quantumult X":                     {Icon: ":quantumult_x:", Font: settings.FontAppIcon},
	"qutebrowser":                      {Icon: ":qute_browser:", Font: settings.FontAppIcon},
	"Raindrop.io":                      {Icon: ":raindrop_io:", Font: settings.FontAppIcon},
	"Reeder":                           {Icon: ":reeder5:", Font: settings.FontAppIcon},
	"Reminders":                        {Icon: ":reminders:", Font: settings.FontAppIcon},
	"提醒事项":                             {Icon: ":reminders:", Font: settings.FontAppIcon},
	"Rappels":                          {Icon: ":reminders:", Font: settings.FontAppIcon},
	"Replit":                           {Icon: ":replit:", Font: settings.FontAppIcon},
	"Rider":                            {Icon: ":rider:", Font: settings.FontAppIcon},
	"JetBrains Rider":                  {Icon: ":rider:", Font: settings.FontAppIcon},
	"Rio":                              {Icon: ":rio:", Font: settings.FontAppIcon},
	"Royal TSX":                        {Icon: ":royaltsx:", Font: settings.FontAppIcon},
	"Safari":                           {Icon: ":safari:", Font: settings.FontAppIcon},
	"Safari浏览器":                        {Icon: ":safari:", Font: settings.FontAppIcon},
	"Safari Technology Preview":        {Icon: ":safari:", Font: settings.FontAppIcon},
	"Sequel Ace":                       {Icon: ":sequel_ace:", Font: settings.FontAppIcon},
	"Sequel Pro":                       {Icon: ":sequel_pro:", Font: settings.FontAppIcon},
	"Setapp":                           {Icon: ":setapp:", Font: settings.FontAppIcon},
	"SF Symbols":                       {Icon: ":sf_symbols:", Font: settings.FontAppIcon},
	"Signal":                           {Icon: ":signal:", Font: settings.FontAppIcon},
	"sioyek":                           {Icon: ":sioyek:", Font: settings.FontAppIcon},
	"Sketch":                           {Icon: ":sketch:", Font: settings.FontAppIcon},
	"Skype":                            {Icon: ":skype:", Font: settings.FontAppIcon},
	"Slack":                            {Icon: ":slack:", Font: settings.FontAppIcon},
	"Snapchat":                         {Icon: "󰒶", Font: settings.FontIcon},
	"Spark Desktop":                    {Icon: ":spark:", Font: settings.FontAppIcon},
	"Spotify":                          {Icon: ":spotify:", Font: settings.FontAppIcon},
	"Spotlight":                        {Icon: ":spotlight:", Font: settings.FontAppIcon},
	"Sublime Text":                     {Icon: ":sublime_text:", Font: settings.FontAppIcon},
	"superProductivity":                {Icon: ":superproductivity:", Font: settings.FontAppIcon},
	"Tana":                             {Icon: ":tana:", Font: settings.FontAppIcon},
	"TeamSpeak 3":                      {Icon: ":team_speak:", Font: settings.FontAppIcon},
	"Telegram":                         {Icon: ":telegram:", Font: settings.FontAppIcon},
	"Terminal":                         {Icon: ":terminal:", Font: settings.FontAppIcon},
	"Ghostty":                          {Icon: ":ghostty:", Font: settings.FontAppIcon},
	"终端":                               {Icon: ":terminal:", Font: settings.FontAppIcon},
	"Typora":                           {Icon: ":text:", Font: settings.FontAppIcon},
	"Microsoft To Do":                  {Icon: ":things:", Font: settings.FontAppIcon},
	"Things":                           {Icon: ":things:", Font: settings.FontAppIcon},
	"Thunderbird":                      {Icon: ":thunderbird:", Font: settings.FontAppIcon},
	"TickTick":                         {Icon: ":tick_tick:", Font: settings.FontAppIcon},
	"TIDAL":                            {Icon: ":tidal:", Font: settings.FontAppIcon},
	"Tiny RDM":                         {Icon: ":tinyrdm:", Font: settings.FontAppIcon},
	"Todoist":                          {Icon: ":todoist:", Font: settings.FontAppIcon},
	"Toggl Track":                      {Icon: ":toggl_track:", Font: settings.FontAppIcon},
	"Tor Browser":                      {Icon: ":tor_browser:", Font: settings.FontAppIcon},
	"Tower":                            {Icon: ":tower:", Font: settings.FontAppIcon},
	"Transmit":                         {Icon: ":transmit:", Font: settings.FontAppIcon},
	"Trello":                           {Icon: ":trello:", Font: settings.FontAppIcon},
	"Tweetbot":                         {Icon: ":twitter:", Font: settings.FontAppIcon},
	"Twitter":                          {Icon: ":twitter:", Font: settings.FontAppIcon},
	"MacVim":                           {Icon: ":vim:", Font: settings.FontAppIcon},
	"Vim":                              {Icon: ":vim:", Font: settings.FontAppIcon},
	"VimR":                             {Icon: ":vim:", Font: settings.FontAppIcon},
	"Vivaldi":                          {Icon: ":vivaldi:", Font: settings.FontAppIcon},
	"VLC":                              {Icon: ":vlc:", Font: settings.FontAppIcon},
	"VMware Fusion":                    {Icon: ":vmware_fusion:", Font: settings.FontAppIcon},
	"VSCodium":                         {Icon: ":vscodium:", Font: settings.FontAppIcon},
	"Antigravity":                      {Icon: ":code:", Font: settings.FontAppIcon},
	"Warp":                             {Icon: ":warp:", Font: settings.FontAppIcon},
	"WebStorm":                         {Icon: ":web_storm:", Font: settings.FontAppIcon},
	"微信":                               {Icon: ":wechat:", Font: settings.FontAppIcon},
	"WeChat":                           {Icon: ":wechat:", Font: settings.FontAppIcon},
	"企业微信":                             {Icon: ":wecom:", Font: settings.FontAppIcon},
	"WeCom":                            {Icon: ":wecom:", Font: settings.FontAppIcon},
	"WezTerm":                          {Icon: ":wezterm:", Font: settings.FontAppIcon},
	"WhatsApp":                         {Icon: ":whats_app:", Font: settings.FontAppIcon},
	"\u200eWhatsApp":                   {Icon: ":whats_app:", Font: settings.FontAppIcon},
	"Xcode":                            {Icon: ":xcode:", Font: settings.FontAppIcon},
	"Yandex Music":                     {Icon: ":yandex_music:", Font: settings.FontAppIcon},
	"Yuque":                            {Icon: ":yuque:", Font: settings.FontAppIcon},
	"语雀":                               {Icon: ":yuque:", Font: settings.FontAppIcon},
	"Zed":                              {Icon: ":zed:", Font: settings.FontAppIcon},
	"Zeplin":                           {Icon: ":zeplin:", Font: settings.FontAppIcon},
	"zoom.us":                          {Icon: ":zoom:", Font: settings.FontAppIcon},
	"Zotero":                           {Icon: ":zotero:", Font: settings.FontAppIcon},
	"Zulip":                            {Icon: ":zulip:", Font: settings.FontAppIcon},
}